run:
  timeout: 10m
linters:
  enable:
    - asciicheck
    - depguard
    - dogsled
    - durationcheck
    - errcheck
    - errorlint
    - exportloopref
    - gofmt
    - gofumpt
    - goimports
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - megacheck
    - misspell
    - nakedret
    - nolintlint
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unused
linters-settings:
  gosec:
    # Exclude generated files
    exclude-generated: true
  gofmt:
    # simplify code: gofmt with `-s` option, true by default
    simplify: true