require: rubocop-rails

inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'bin/*'
    - 'config.ru'
    - 'db/schema.rb'
    - 'Rakefile'
    - 'vendor/bundle/**/*'

# LineLength metrics seems to complicate any other rules.
# It should probably be enabled last, if ever.
# https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Metrics/LineLength
Metrics/LineLength:
  Enabled: false

# Gems are better manually ordered
# https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Bundler/OrderedGems
Bundler/OrderedGems:
  Enabled: false

# This cop checks for a line break before the first argument in a multi-line method call.
# This makes it easier to add remove arguments
# https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Layout/FirstMethodArgumentLineBreak
Layout/FirstMethodArgumentLineBreak:
  Enabled: true

# Empty method should be declared over 2 lines, not 1
# https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/EmptyMethod
Style/EmptyMethod:
  EnforcedStyle: expanded

# All lambdas should be declared with ->() {} syntax
# https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/Lambda
Style/Lambda:
  EnforcedStyle: literal

# %w[] array syntax is sometimes confusing, we should not enforce it
# https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/SymbolArray
Style/SymbolArray:
  Enabled: false

# %w[] array syntax is sometimes confusing, we should not enforce it
# https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/WordArray
Style/WordArray:
  Enabled: false