language: node_js
sudo: required
node_js:
    - 'lts/*'
    - '8.9.0'
    - '10'

os:
    - linux
    - osx
    - windows

cache:
    directories:
        - node_modules

script:
    - npm i --ignore-scripts
    - npm test
