sudo: false
language: ruby
cache: bundler
services:
  - postgresql

branches:
  only:
    - master

before_install:
  - gem update --system # https://github.com/travis-ci/travis-ci/issues/8978
  - nvm install

before_script:
  - psql -c 'create database volunteer_test;' -U postgres
  - psql -c 'create role volunteer with login superuser;' -U postgres
  - bundle exec rake db:test:prepare
  - bin/rails db:migrate
  - npm install

script: $TASK

env:
  - TASK="bundle exec rake brakeman"
  - TASK="bundle exec rake test"
  - TASK="npm test"
  - TASK="bundle exec script/sourceclear.sh"

matrix:
  allow_failures:
    - env: TASK="bundle exec script/sourceclear.sh"
