language: elixir
elixir:
  - 1.4.1
otp_release:
  - 19.1
branches:
    only:
      - master
      - staging
      - trying

cache:
  directories:
    - _build
    - deps

install:
  - if [ $TYPE != script ]; then mix do local.rebar --force, local.hex --force, deps.get; fi
  - if [ $TYPE = script ] && [ $TRAVIS_BRANCH != master ]; then sh script/setup; fi

script:
  - if [ $TYPE = test ]; then mix test; fi
  - if [ $TYPE = dogma ]; then mix dogma; fi
  - if [ $TYPE = dialyzer ]; then mix dialyzer --halt-exit-status; fi
  - if [ $TYPE = script ] && [ $TRAVIS_BRANCH != master ]; then sh script/test; fi

env:
  - TYPE=test
  - TYPE=dogma
  - TYPE=dialyzer

matrix:
  fast_finish: true

  include:
    - env: TYPE=script
      sudo: true
      language: minimal
      elixir: false
      otp_release: false
      cache: false

notifications:
  email: false
