test-config-file-slug:
    title: Configuration Title
    multisite: false
    php: 8.1
    wordpress: 6.1
    mu-plugins: demo
    app-code: ../vip-go-skeleton
    elasticsearch: true
    phpmyadmin: true
    xdebug: true
