name: "Sticky Pull Request Comment"
description: "Create comment on pull request, if exists update that comment."
author: "marocchino"
inputs:
  header:
    description: "Header to determine if the comment is to be updated, not shown on screen"
    required: false
  append:
    description: "Indicate if new comment messages should be appended to previous comment message"
    required: false
  recreate:
    description: "Indicate if previous comment should be removed before creating a new comment"
    required: false
  message:
    description: "comment message"
    required: false
  path:
    description: "path to file containing comment message"
    required: false
  number:
    description: "pull request number for push event"
    required: false
  delete:
    description: "delete the previously created comment"
    required: false
  repo:
    description: "Limited use on github enterprise. Note that When you trying changing a repo, be aware that GITHUB_TOKEN should also use that repo's. If not set, the current repo is used by default."
    required: false
  GITHUB_TOKEN:
    description: "set secrets.GITHUB_TOKEN here"
    required: true
runs:
  using: "node12"
  main: "lib/main.js"
