name: "Your name here"
description: "Provide a description here"
author: "Your name or organization here"
inputs:
  message:
    description: "comment message"
  GITHUB_TOKEN:
    description: "set secrets.GITHUB_TOKEN here"
runs:
  using: "node12"
  main: "lib/main.js"
