[tool.codespell]
skip = '.git,*.pdf,*.svg,.tox'
ignore-regex = "\\\\[fnrstv]"
#
# ignore-words-list = ''

[tool.pytest.ini_options]
addopts = [
    "--strict-config",
    "--strict-markers",
]
markers = ["online"]
filterwarnings = [
    "error",
    '''ignore:datetime\.datetime\.utcfromtimestamp\(\) is deprecated and scheduled for removal in a future version.*:DeprecationWarning''',
    '''ignore:There is no current event loop:DeprecationWarning''',
    '''ignore:make_current is deprecated; start the event loop first:DeprecationWarning''',
    '''ignore:clear_current is deprecated:DeprecationWarning''',
    '''ignore:the \(type, exc, tb\) signature of throw\(\) is deprecated, use the single-arg signature instead.:DeprecationWarning''',
]

[tool.ruff]
select = [
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "COM", # flake8-commas
    "E",   # pycodestyle error
    "F",   # pyflakes
    "I",   # isort
    "ISC", # flake8-implicit-str-concat
    "PIE", # flake8-pie
    "RUF", # Ruff-specific rules
    "UP",  # pyupgrade
    "W",   # pycodestyle warning
]
line-length = 110
target-version = "py38"

[tool.ruff.isort]
known-first-party = ["vcr"]
