name: haproxy-operator

resources:
  limits:
    cpu: '2'
    memory: 4Gi
  requests:
    cpu: 200m
    memory: 512Mi

image:
  repository: ghcr.io/six-group/haproxy-operator

helper:
  image:
    repository: rhel8/support-tools
    tag: 8.9

rsyslog:
  image:
    repository: rhel8/rsyslog
    tag: 8.9