version: 2.1

workflows:
  build:
    jobs:
      - test:
          version: 8-stretch
      - test:
          version: 10-stretch
      - test:
          version: lts-stretch
      - test:
          version: current-stretch

jobs:
  test:
    parameters:
      version:
        type: string

    docker:
      - image: circleci/node:<< parameters.version >>

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # Build the lib
      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Lint + Test
      - run: npm run test
