apiVersion: v2
name: bors-ng
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "latest"

maintainers: # (optional)
  - name: The maintainers name (required for each maintainer)
    email: The maintainers email (optional for each maintainer)
    url: A URL for the maintainer (optional for each maintainer)

dependencies:
- name: postgresql
  condition: postgresql.enabled
  version: "10.3.14"
  repository: https://charts.bitnami.com/bitnami
