apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-cluster-reader: 'true'
    rbac.authorization.k8s.io/aggregate-to-view: 'true'
  name: aggregate-haproxy-view
rules:
- apiGroups:
  - config.haproxy.com
  resources:
    - listens
    - frontends
    - backends
    - resolvers
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - proxy.haproxy.com
  resources:
    - instances
  verbs:
    - get
    - list
    - watch