apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: 'true'
    rbac.authorization.k8s.io/aggregate-to-edit: 'true'
  name: aggregate-haproxy-edit
rules:
- apiGroups:
  - config.haproxy.com
  resources:
    - listens
    - frontends
    - backends
    - resolvers
  verbs:
    - create
    - update
    - patch
    - delete
- apiGroups:
    - proxy.haproxy.com
  resources:
    - instances
  verbs:
    - create
    - update
    - patch
    - delete