kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: {{ .Values.name }}
    app.openshift.io/runtime: golang
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      serviceAccountName: {{ .Values.name }}
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
          imagePullPolicy: IfNotPresent
          env:
            - name: LEADER_ELECT
              value: 'true'
            - name: HELPER_IMAGE
              value: {{ .Values.helper.image.repository }}:{{ .Values.helper.image.tag }}
            - name: RSYSLOG_IMAGE
              value: {{ .Values.rsyslog.image.repository }}:{{ .Values.rsyslog.image.tag }}
          ports:
            - containerPort: 8080
              name: metrics
            - containerPort: 8081
              name: health-probe
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
