# NOTE: This name appears in GitHub's Checks API and in workflow's status badge.
name: ci-lint

# Trigger the workflow when:
on:
  # A push occurs to one of the matched branches.
  push:
    branches:
      - main
      - stable/*
  # Or when a pull request event occurs for a pull request against one of the
  # matched branches.
  pull_request:
    branches:
      - main
      - stable/*

jobs:
  lint-go:
    name: lint-go
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          # Fetch all history so gitlint can check the relevant commits.
          fetch-depth: '0'
      - name: Set up Python 3
        uses: actions/setup-python@v2.3.2
        with:
          python-version: '3.x'
      - name: Install gitlint
        run: |
          python -m pip install gitlint
      - name: Lint git commits
        run: |
          make lint-git
        # Always run this step so that all linting errors can be seen at once.
        # Skip this step for dependabot pull requests.
        if: always() && github.actor != 'dependabot[bot]'
      - name: Lint Go
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.43
        # Always run this step so that all linting errors can be seen at once.
        if: always()
