name: Comment on Pull Request
on:
  pull_request:

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build
      - uses: ./
        with:
          header: FromPR
          recreate: true
          message: |
            Test ${{ github.sha }} is successfully ended.
            This is message from PR.
      - uses: ./
        with:
          header: FromPR
          append: true
          message: |
            Append message.
