name: Comment on Pull Request
on:
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: ./
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: |
            Test ${{ github.sha }} is successfully ended.
