name: E2E Tests for Dev Env

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Run E2E Tests on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: npm
          cache-dependency-path: npm-shrinkwrap.json

      - name: Install dependencies
        run: npm ci

      - name: Install Docker
        run: |
          brew install docker docker-compose
          colima start
          echo "DOCKER_HOST=unix://$HOME/.colima/default/docker.sock" >> $GITHUB_ENV
          sudo ln -s /Users/runner/.colima/default/docker.sock /var/run/docker.sock || true
        if: contains(matrix.os, 'macos')

      - run: npm config set script-shell bash
        if: contains(matrix.os, 'windows')

      - name: Run tests
        run: npm run test:e2e:dev-env
