name: Publish 🚀

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'

jobs:
  deployment:
    name: Publish the image
    runs-on: ubuntu-latest
    env:
      AWS_CLI_VERSION: 2.9.8
      ALPINE_VERSION: 3.17
    steps:
      - name: Check out repository code
        uses: actions/checkout@main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/arm64

      - name: Log in to GitHub registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/awscliv2:${{ env.AWS_CLI_VERSION }}

      - name: Build the image
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          buil-args: |
            AWS_CLI_VERSION=${{ env.AWS_CLI_VERSION }}
            ALPINE_VERSION=${{ env.ALPINE_VERSION }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/awscliv2:${{ env.AWS_CLI_VERSION }}
