name: Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: |
          mkdir -p ./pr
          echo ${{ github.event.number }} | tee ./pr/number
          npm run all | tee ./pr/all_result
      - uses: actions/upload-artifact@v2
        if: ${{ github.event_name == 'pull_request' }}
        with:
          name: all
          path: pr/
